### ISSUE TITLE
Remove patterns/components/JS

### ISSUE THREAD

**Issue by julio8a** [Esri/calcite-web#1088]
Since we are creating a calcite-components repository, we need to remove all of the components from calcite-web.

- [x] __Merged__ PR: #1092 [tabs](https://github.com/ArcGIS/calcite-components/issues/8) 
- [x] __Merged__ PR: #1091 [alerts](https://github.com/ArcGIS/calcite-components/issues/15) 
- [x] __Merged__ PR: #1089 [cards](https://github.com/ArcGIS/calcite-components/issues/52) 
- [ ] PR: #1100  [checkboxes & Radio](https://github.com/ArcGIS/calcite-components/issues/1) documentation
- [ ] PR: #1099 [selects](https://github.com/ArcGIS/calcite-components/issues/2) documentation
- [ ] PR: #1098 [toggle switch](https://github.com/ArcGIS/calcite-components/issues/3)
- [ ] PR: #1097 [slider](https://github.com/ArcGIS/calcite-components/issues/4)
- [ ] PR: #1094 [radio group](https://github.com/ArcGIS/calcite-components/issues/5)
- [ ] PR: #1090 [dropdown](https://github.com/ArcGIS/calcite-components/issues/6)
- [ ] PR: #1096[loader](https://github.com/ArcGIS/calcite-components/issues/7) 
- [ ] PR: #1092 [modal](https://github.com/ArcGIS/calcite-components/issues/9) 
- [ ] PR: #1093[accordion](https://github.com/ArcGIS/calcite-components/issues/10) 
- [ ] PR: #1090 [filter dropdown](https://github.com/ArcGIS/calcite-components/issues/46) 
- [ ] JS (will wait for other to get merged before working on this one)

**Comment by paulcpederson** [comment]
Should we still provide our default styles for browser-native checkboxes and selects?

**Comment by julio8a** [comment]
@paulcpederson, Yes. Good point.

**Comment by julio8a** [comment]
Moving components to calcite-components. JS can stay here for 1.x
