### ISSUE TITLE
v1.0.0 Checklist

### ISSUE THREAD

**Issue by paulcpederson** [Esri/calcite-web#56]
All of the following should be completed, documented, browser tested, and work responsively.
### Type
- [ ] Header
  - [x] documented
  - [x] css
  - [x] responsive
  - [ ] browser tested
- [ ] Body
  - [x] documented
  - [x] css
  - [x] responsive
  - [ ] browser tested
- [ ] Secondary
  - [x] documented
  - [x] css
  - [x] responsive
  - [ ] browser tested
- [ ] Code
  - [x] documented
  - [x] css
  - [x] responsive
  - [ ] browser tested
- [ ] Font modifiers
  - [x] documented
  - [x] css
  - [x] responsive
  - [ ] browser tested
- [ ] Links
  - [x] documented
  - [x] css
  - [x] responsive
  - [ ] browser tested
- [ ] Basic styles for all type elements
  - [x] documented
  - [x] css
  - [x] responsive
  - [ ] browser tested
### Grid
- [ ] Container
  - [x] documented
  - [x] css
  - [x] responsive
  - [ ] browser tested
- [ ] Columns
  - [x] documented
  - [x] css
  - [x] responsive
  - [ ] browser tested
- [ ] Responsive Columns
  - [x] documented
  - [x] css
  - [x] responsive
  - [ ] browser tested
- [ ] Nested Columns
  - [x] documented
  - [x] css
  - [x] responsive
  - [ ] browser tested
- [ ] Rows
  - [x] documented
  - [x] css
  - [x] responsive
  - [ ] browser tested
- [x] Block Groups
  - [x] documented
  - [x] css
  - [x] responsive
  - [x] browser tested
- [x] Responsive Block Groups
  - [x] documented
  - [x] css
  - [x] responsive
  - [x] browser tested
- [x] Grid Helpers
  - [x] documented
  - [x] css
  - [x] responsive
  - [x] browser tested
- [ ] Pre & Post
  - [x] documented
  - [x] css
  - [x] responsive
  - [ ] browser tested
- [ ] Leader & Trailer
  - [x] documented
  - [x] css
  - [x] responsive
  - [ ] browser tested
- [ ] First & Last
  - [x] documented
  - [x] css
  - [x] responsive
  - [ ] browser tested
- [ ] Show & Hide
  - [x] documented
  - [x] css
  - [x] responsive
  - [ ] browser tested
- [ ] Left & Right
  - [x] documented
  - [x] css
  - [x] responsive
  - [ ] browser tested
- [ ] Sticky
  - [x] documented
  - [x] css
  - [ ] responsive
  - [ ] browser tested
### Color
- [x] Calcite Web Color Pallette
  - [x] documented
  - [x] css
  - [x] responsive
  - [x] browser tested
### Components
- [ ] Buttons
  - [x] documented
  - [x] css
  - [x] responsive
  - [ ] browser tested
- [ ] Button Group
  - [x] documented
  - [x] css
  - [x] responsive
  - [ ] browser tested
- [ ] Tooltips
  - [x] documented
  - [x] css
  - [x] responsive
  - [ ] browser tested
- [ ] Click Dropdowns
  - [x] documented
  - [x] css
  - [x] responsive
  - [ ] browser tested
  - [x] javscript
- [ ] Alerts
  - [x] documented
  - [x] css
  - [x] responsive
  - [ ] browser tested
- [ ] Breadcrumbs
  - [x] documented
  - [x] css
  - [x] responsive
  - [ ] browser tested
- [ ] Pagination
  - [x] documented
  - [x] css
  - [x] responsive
  - [ ] browser tested
- [ ] Loader
  - [x] documented
  - [x] css
  - [x] responsive
  - [ ] browser tested
- [ ] Panels
  - [x] documented
  - [x] css
  - [x] responsive
  - [ ] browser tested
- [ ] Tables
  - [x] documented
  - [x] css
  - [x] responsive
  - [ ] browser tested
- [ ] Form Elements
  - [x] documented
  - [x] css
  - [x] responsive
  - [ ] browser tested
- [ ] Esri logo
  - [x] documented
  - [x] css
  - [x] responsive
  - [ ] browser tested
### PATTERNS
- [ ] Top Nav
  - [x] documented
  - [x] css
  - [x] responsive
  - [ ] browser tested
- [ ] Search (Top Nav)
  - [x] documented
  - [x] css
  - [x] responsive
  - [ ] browser tested
- [ ] Sign In (Top Nav)
  - [x] documented
  - [x] css
  - [x] responsive
  - [ ] browser tested
- [ ] User Nav (Top Nav)
  - [x] documented
  - [x] css
  - [x] responsive
  - [ ] browser tested
- [ ] Sub Nav
  - [x] documented
  - [x] css
  - [x] responsive
  - [ ] browser tested
- [ ] Third Nav
  - [x] documented
  - [x] css
  - [x] responsive
  - [ ] browser tested
- [ ] Side Nav
  - [x] documented
  - [x] css
  - [x] responsive
  - [ ] browser tested
- [ ] Expanding Nav
  - [x] documented
  - [x] css
  - [x] responsive
  - [ ] browser tested
  - [ ] javascript
- [ ] Footer
  - [x] documented
  - [x] css
  - [x] responsive
  - [ ] browser tested
- [ ] Modals
  - [x] documented
  - [x] css
  - [x] responsive
  - [ ] browser tested
  - [x] javascript
- [ ] Tabs
  - [x] documented
  - [x] css
  - [x] responsive
  - [ ] browser tested
  - [x] javascript
- [ ] Accordions
  - [x] documented
  - [x] css
  - [x] responsive
  - [ ] browser tested
  - [x] javascript
- [ ] Drawer
  - [x] documented
  - [x] css
  - [x] responsive
  - [ ] browser tested
  - [x] javascript
